#
# HSS Payload Generator - configuration file
#

set-name: 'PolarFire-SoC-HSS::seL4'

hart-entry-points: {u54_1: '0x89000000', u54_2: '0x89000000', u54_3: '0x89000000', u54_4: '0x88000000'}

payloads:
#  With certain HSS configurations u-boot.bin is required.
#  Otherwise seL4 hart waits forever at the end of HSS startup sequence.
#
#  /path/to/u-boot.bin: {exec-addr: '0x89000000', owner-hart: u54_1, secondary-hart: u54_2, secondary-hart: u54_3, priv-mode: prv_s}
  sel4payload: {exec-addr: '0x88000000', owner-hart: u54_4, priv-mode: prv_s}

