#
# HSS Payload Generator - configuration file
#

set-name: 'PolarFire-SoC-HSS::seL4'

hart-entry-points: {u54_1: '0x80200000', u54_2: '0x84000000', u54_3: '0x84000000', u54_4: '0x84000000'}

payloads:
  sel4payload: {exec-addr: '0x80200000', owner-hart: u54_1, priv-mode: prv_s}

